# Generated by Django 4.0.3 on 2022-03-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamento_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=70, verbose_name='nome'),
        ),
    ]
