# Generated by Django 4.0.3 on 2022-03-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_user'),
        ('documentos', '0002_documento_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario', verbose_name='Pertence a'),
            preserve_default=False,
        ),
    ]
