# Generated by Django 4.0.3 on 2022-03-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_company'),
        ('documentos', '0003_alter_documento_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='file',
            field=models.FileField(default='', upload_to='Documentos', verbose_name='arquivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario', verbose_name='pertence a'),
        ),
    ]
