# Generated by Django 4.0.3 on 2022-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0002_registrohoraextra_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Horas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='reason',
            field=models.CharField(max_length=50, verbose_name='Motivo'),
        ),
    ]
