# Generated by Django 4.0.3 on 2022-04-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_registrohoraextra_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
